jobs:
  include:
  - script:
    - docker-compose up -d
    # test that flink metrics arrive in prometheus
    - until $(curl -s "http://localhost:9090/api/v1/query?query=flink_jobmanager_job_uptime" | jq -e '.data.result != []'); do sleep 1; done
    # test that prometheus-json-exporter metrics arrive in prometheus
    - until $(curl -s "http://localhost:9090/api/v1/query?query=flink_api_jobs_running" | grep -q CarTopSpeedWindowingExample); do sleep 1; done
