---
version: '3'

services:
  jobmanager:
    build: ./flink
    container_name: jobmanager
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    build: ./flink
    container_name: taskmanager
    links:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  job:
    build: ./flink
    container_name: job
    links:
      - jobmanager
    depends_on:
      - taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: job -p 4 /opt/flink/examples/streaming/TopSpeedWindowing.jar

  prometheus-json-exporter:
    build: ./prometheus-json-exporter
    container_name: prometheus-json-exporter
    ports:
      - 7979:7979
    links:
      - jobmanager
    command: http://jobmanager:8081/jobs/overview ./config.yml
    volumes:
      - ./prometheus-json-exporter/config.yml:/config.yml

  prometheus:
    image: prom/prometheus:v2.3.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
