- name: flink_api_jobs
  type: object
  path: $.jobs[*]?(@.state == "RUNNING")
  labels:
    job_name: $.name
  values:
    running: 1

- name: flink_api_jobs
  type: object
  path: $.jobs[*]?(@.state == "FINISHED")
  labels:
    job_name: $.name
  values:
    finished: 1
