---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
- flink.rules.yml

scrape_configs:
- job_name: 'job-cluster'
  static_configs:
  - targets: ['job-cluster:9249']

- job_name: 'taskmanager1'
  static_configs:
  - targets: ['taskmanager1:9249']

- job_name: 'taskmanager2'
  static_configs:
  - targets: ['taskmanager2:9249']
