global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - flink.rules.yml

scrape_configs:
  - job_name: 'flink-api'
    static_configs:
      - targets: ['prometheus-json-exporter:7979']

  - job_name: 'job-cluster'
    static_configs:
      - targets: ['job-cluster:9249']

  - job_name: 'taskmanager1'
    static_configs:
      - targets: ['taskmanager1:9249']

  - job_name: 'taskmanager2'
    static_configs:
      - targets: ['taskmanager2:9249']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
